name: Codex YAML CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y yamllint systemd
      - name: Lint YAML
        run: yamllint codex_node.yaml
      - name: Verify systemd service
        run: systemd-analyze verify systemd/zedec-v3.service
