name: ZEDEC Master CI Pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Commit Message
        run: echo 'COMMIT_MSG="... ... ...ZEDEC POST QUANTUM OS is free for all to use... ... ..."' >> $GITHUB_ENV

  test-and-build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running unit tests..."
          # insert test command

      - name: Build Project
        run: |
          echo "Building project..."
          # insert build command

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run CodeQL Security Scan
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v2
